### ISSUE TITLE
Add new annotation to set mapping between two fields

### ISSUE THREAD

**Issue by jbreathe** [jbreathe/corgi#11]
For example, you have two structures with two semantically identical fields, but they named differently, for some reasons:
```java
class A {
    String color;
}
class B {
    String colour;
}
```
And you want be able to add mapping between them, like so:
```java
@Mapping(fieldMappings = {
        @FieldMapping(from = "color", to = "colour")
})
A map(B b);

**Comment by aivinog1** [comment]
@jbreathe Hello, I would like to take this, if you don't mind.

**Comment by jbreathe** [comment]
@aivinog1 
Sure, my friend!

**Comment by jbreathe** [comment]
@aivinog1 
Sorry, my fault.
It must be:
```
from = "colour", to = "color"
```
in the task.

**Comment by aivinog1** [comment]
@jbreathe Are you sure? It leads to some misunderstanding even for two of us :) Maybe we should name them like `sourceField` and `targetField`?

**Comment by jbreathe** [comment]
@aivinog1 
Maybe. Or just source/target like in mapstruct.

**Comment by aivinog1** [comment]
@jbreathe Got it, I'll rename them.
